export const CONSTANT = {
  AWS_BUCKET_URL: localStorage.getItem("aws_bucket_url"),
  LOGIN_REDIRECT_PATH: "/login",
  DASHBOARD_REDIRECT_PATH: "/dashboardcontroller",
  WITHOUT_LOGIN_PAGE: ["/", "/login"],
  DEFAULT_LATITUDE: 23.009529,
  DEFAULT_LONGITUDE: 72.510963,
  SEND_ERROR_REPORT_TO: "anand.esprit@gmail.com",
  MAX_EMAIL_ATTEMPT: 5,
  DEFAULT_USER_AVATAR_ID: 3,
  API_KEY: "g9d54312a5c53ce30738dcd8838c5128",
  MASTER_DOMAIN: "https://everythingcivic.com/",
  SUPER_ADMIN_ID: 1,
  SUPER_ADMIN_ROLE_ID: 1,
  EMAIL_TEMPLATE: {
    ADMIN: {
      FORGOT_PASSWORD: 1,
      RESET_PASSWORD: 2,
    },
  },
  PER_PAGE_RECORD: [
    { id: "50", value: "50 per page" },
    { id: "100", value: "100 per page" },
    { id: "500", value: "500 per page" },
    { id: "1000", value: "1000 per page" },
  ],
  ROLE: {
    ADMIN: "1",
    COMMISSIONER: "2",
    DIRECTOR: "3",
    DIVISIONAL_HEAD: "4",
    WARD_OFFICER: "5",
    CIVILIANS: "6",
    OPERATOR: "7",
  },
  PLATFORM: {
    ANDROID: 300,
    IPHONE: 301,
  },
  PLATFORM_ARRAY: [
    { id: 300, name: "ANDROID" },
    { id: 301, name: "IPHONE" },
  ],
  JOB: {
    TYPE: [],
  },
  FROM_APP: {
    CITIZEN: 1,
    OFFICER: 2,
    WEB: 3,
  },
  APP_MASTER: {
    IS_ACTIVE: {
      YES: 1,
      NO: 0,
    },
    MAINTAINANCE_MODE: {
      YES: 1,
      NO: 0,
    },
    ID: {
      AGARTALA: 1,
      MERA_AGRA: 2,
      AMC: 3,
      AUDA: 4,
      DDA: 5,
      DEHRADUN: 6,
      FARIDABAD: 7,
      GHAZIABAD: 8,
      GURUGRAM: 9,
      HFAS: 10,
      INDORE: 11,
      JABALPUR: 12,
      JODHPUR: 13,
      JUNAGADH: 14,
      LUCKNOW: 15,
      MCD: 16,
      PORBANDAR: 17,
      SMARTCITY: 18,
      UJJAIN: 19,
      KASHI: 20,
      // NDMC: 20,
      // SURAT: 21,
    },
  },
  MSG: {
    TYPE: {
      SOS: "SOS",
      CERTIFICATE: "Certificate",
      COMPLAINTREG: "ComplaintReg",
      RESETPASSWORDURL: "ResetPasswordURL",
      TRADELICENSE: "TradeLicense",
      WATERCONNECTION: "WaterConnection",
      OTPVERIFICATION: "OTPVerification",
      CHALLANPAYMENTRECEIVECACKZO: "ChallanPaymentReceivedACKZO",
      CHALLANPAYMENTRECEIVEDACKMOH: "ChallanPaymentReceivedACKMOH",
      CHALLANSUBMIT: "ChallanSubmit",
      ACCOUNT_APPROVED: "account_approved",
    },
  },
};
